apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ghcr.io/randsw/kafka-consumer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name:  BOOTSTRAP_SERVERS
          value:  ENVVARVALUE
        - name:  TOPIC
          value:  example
        - name:  SCHEMA_REGISTRY_URL
          value:  ENVVARVALUE
        - name:  GROUP_ID
          value:  example-group
        - name:  OUT_ADDRESS
          value:  ENVVARVALUE  
        volumeMounts:
        - name: kafka-ca-cert
          readOnly: true
          mountPath: "/tmp/ca"
        - name: client-mtls
          readOnly: true
          mountPath: "/tmp/client"
      volumes:
        - name: cluster-ca-cert
          secret:
            secretName: cluster-ca-cert
            defaultMode: 0400
        - name: client-mtls
          secret:
            secretName: user-ca
            defaultMode: 0400
