apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: producer
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: ghcr.io/randsw/kafka-producer
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name:  KAFKA_URL
          value: kafka-cluster-kafka-bootstrap:9093
        - name:  TOPIC
          value: example-topic
        - name:  SCHEMA_REGISTRY_URL
          value: confluent-schema-registry:8081
        volumeMounts:
        - name: cluster-ca-cert
          readOnly: true
          mountPath: "/tmp/ca"
        - name: client-mtls
          readOnly: true
          mountPath: "/tmp/client"
      volumes:
        - name: cluster-ca-cert
          secret:
            secretName: kafka-cluster-cluster-ca-cert
            defaultMode: 0444
        - name: client-mtls
          secret:
            secretName: producer-user
            defaultMode: 0444
